### ISSUE TITLE
Crash on device when trying to open the custom tab

### ISSUE THREAD

**Issue by PrerakPrek** [onedevapp/Unity_ChromeCustomTabs#1]
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime FATAL EXCEPTION: main
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime Process: com.packagename.packagename, PID: 10767
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime java.lang.NoSuchMethodError: No virtual method setDefaultColorSchemeParams(Landroidx/browser/customtabs/CustomTabColorSchemeParams;)Landroidx/browser/customtabs/CustomTabsIntent$Builder; in class Landroidx/browser/customtabs/CustomTabsIntent$Builder; or its super classes (declaration of 'androidx.browser.customtabs.CustomTabsIntent$Builder' appears in /data/app/~~1I8QNkStzFhy3-gitG1R2g==/com.packagename.packagename-wWkHAnGk9mT44S4xh6R-Yw==/base.apk)
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime 	at com.onedevapp.customchrometabs.CustomHeadlessActivity.openCustomTab(CustomHeadlessActivity.java:116)
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime 	at com.onedevapp.customchrometabs.CustomHeadlessActivity.handleIntent(CustomHeadlessActivity.java:91)
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime 	at com.onedevapp.customchrometabs.CustomHeadlessActivity.onCreate(CustomHeadlessActivity.java:45)
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime 	at android.app.Activity.performCreate(Activity.java:8595)
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime 	at android.app.Activity.performCreate(Activity.java:8573)
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:106)
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime 	at android.os.Looper.loopOnce(Looper.java:205)
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:294)
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:8177)
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
2024/09/20 21:09:22.930 10767 10767 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by PrerakPrek** [comment]
closing this issue as it was a error between dependencies of this plugin and UniWebView.
